---
- name: sample_book
  hosts: dev-servers
  remote_user: root
  become: true
  tasks:
    - name: maven deplay with nexus
      command: mvn -f /var/lib/jenkins/workspace/DevOps-IOC/serveur/pom.xml deploy
      ignore_errors: yes