---
- name: sample_book
  hosts: dev-servers
  remote_user: root
  become: true
  tasks:
    - name:  Deploy MySQL on Kubernetes
      command: kubectl apply -f /var/lib/jenkins/workspace/DevOps-IOC/k8s/mysql.yml
      ignore_errors: yes

