---
- name: sample_book
  hosts: dev-servers
  remote_user: root
  become: true
  tasks:
    - name:  Deploy MySQL on Kubernetes
      command: kubectl apply -f k8s/mysql.yml
      ignore_errors: yes
    - name: Deploy Spring Boot on Kubernetes
      command: kubectl apply -f k8s/app-server.yml
      ignore_errors: yes
    - name: Deploy Angular on Kubernetes
      command: kubectl apply -f k8s/app-client.yml
      ignore_errors: yes
    - name: Expose the App Using an Ingress
      command: kubectl apply -f k8s/ingress-nginx.yml
      ignore_errors: yes
    - name: Create ClusterIssuer
      command: kubectl apply -f k8s/staging-issuer.yml
      ignore_errors: yes
    - name: Create Production ClusterIssuer
      command: kubectl apply -f k8s/prod-issuer.yml
      ignore_errors: yes

