---
- name: sample_book
  hosts: dev-servers
  remote_user: root
  become: true
  tasks:
    - name:  serveur folder
      command: cd serveur
      ignore_errors: yes
    - name: Run maven package
      command: mvn clean package
      ignore_errors: yes
    - name: comme back to first folder
      command: cd ..
      ignore_errors: yes