---
- name: sample_book
  hosts: dev-servers
  remote_user: root
  become: true
  tasks:
    - name: maven deplay with nexus
      command: mvn -f /var/lib/jenkins/workspace/FullSack-CICD/serveur/pom.xml deploy
      ignore_errors: yes
    - name: maven Test with SonarQube
      command: mvn -f /var/lib/jenkins/workspace/FullSack-CICD/serveur/pom.xml sonar:sonar -Dsonar.login=admin -Dsonar.password=sonar
      ignore_errors: yes