---
- name: sample_book
  hosts: dev-servers
  remote_user: root
  become: true
  tasks:
    - name: Run Nexus container with ansible
      command: docker start nexus
      ignore_errors: yes
    - name: Run SonarQube container with ansible
      command: docker start tender_nightingale
      ignore_errors: yes
    - name: Run Prometheus container with ansible
      command: docker start prometheus
      ignore_errors: yes
    - name: Run Grafana container with ansible
      command: docker start grafana
      ignore_errors: yes
    - name: maven Clean package with nexus
      command: mvn -f /var/lib/jenkins/workspace/DevOps-CICD/serveur/pom.xml clean package
      ignore_errors: yes
    - name: maven deplay with nexus
      command: mvn -f /var/lib/jenkins/workspace/DevOps-CICD/serveur/pom.xml deploy
      ignore_errors: yes
    - name: maven Test with SonarQube
      command: mvn -f /var/lib/jenkins/workspace/DevOps-CICD/serveur/pom.xml sonar:sonar -Dsonar.login=admin -Dsonar.password=sonar
      ignore_errors: yes
    - name: Create Spring Boot Application Image
      command: docker build -t mahdijr/app-server:2.0 /var/lib/jenkins/workspace/DevOps-IOC/serveur
      ignore_errors: yes
    - name: Create Angular Application Image
      command: docker build -t mahdijr/app-client:2.0 /var/lib/jenkins/workspace/DevOps-IOC/client
      ignore_errors: yes